### ISSUE TITLE
ValueError: SHA could not be resolved, git returned: b''

### ISSUE THREAD

**Issue by OpenCode** [warp10/rocco#27]
Quando si monta un volume esterno, si ottiene il seguente errore:
```
Traceback (most recent call last):
  File "/rocco/bin/addons_path_generator.py", line 25, in <module>
    in repo.iter_submodules()
  File "/usr/local/lib/python3.9/dist-packages/git/repo/base.py", line 446, in iter_submodules
    return RootModule(self).traverse(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/git/objects/submodule/root.py", line 62, in __init__
    parent_commit=repo.head.commit,
  File "/usr/local/lib/python3.9/dist-packages/git/refs/symbolic.py", line 226, in _get_commit
    obj = self._get_object()
  File "/usr/local/lib/python3.9/dist-packages/git/refs/symbolic.py", line 219, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "/usr/local/lib/python3.9/dist-packages/git/objects/base.py", line 94, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "/usr/local/lib/python3.9/dist-packages/git/db.py", line 40, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "/usr/local/lib/python3.9/dist-packages/git/cmd.py", line 1383, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "/usr/local/lib/python3.9/dist-packages/git/cmd.py", line 1370, in __get_object_header
    return self._parse_object_header(cmd.stdout.readline())
  File "/usr/local/lib/python3.9/dist-packages/git/cmd.py", line 1329, in _parse_object_header
    raise ValueError("SHA could not be resolved, git returned: %r" % (header_line.strip()))
ValueError: SHA could not be resolved, git returned: b''
```

**Comment by OpenCode** [comment]
Possibili soluzioni: https://stackoverflow.com/questions/42972028/gitpython-update-hook-sha-could-not-be-resolved

**Comment by OpenCode** [comment]
Il problema sembra essere tornato
